# Generated by Django 5.1.3 on 2024-11-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAssetsServiceNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=255, unique=True)),
                ('condition', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('warranty_info', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('bank_loan', models.BooleanField(default=False)),
                ('purchase_date', models.DateField()),
                ('expected_life_years', models.PositiveIntegerField()),
                ('asset_end_date', models.DateField()),
                ('months_to_replace', models.PositiveIntegerField()),
                ('three_month_end_alert', models.BooleanField(default=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_of_life_expected_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('straight_line_depreciation_annual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('straight_line_depreciation_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
