# Generated by Django 5.1.3 on 2024-11-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassetsservicenow',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
