# Generated by Django 5.1.3 on 2024-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0002_alter_hardwareassetsservicenow_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareassetsservicenow',
            name='asset_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
